version: 2
updates:
  - package-ecosystem: nuget
    directory: src
    schedule:
      interval: weekly
      day: sunday
      time: 00:00
      timezone: Etc/UTC
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 00:00
      timezone: Etc/UTC
